### ISSUE TITLE
body replaced after 'Aurelia started'

### ISSUE THREAD

**Issue by doktordirk** [aurelia/bootstrapper#40]
and more importantly, after eg app.js constructor

previously eg

``` js
export class App {
  constructor(){
    document.body.appendChild(document.createElement('div'));
  }
...
```

would add a div to the body before eg nav-bar and div page-host. 
after updating from 1.1.2 to 1.1.4 the body gets cleared after the app constructor even though it runs after the 'Aurelia started' log output.

i dont know if that is from the bootstrapper or another package that gets upgraded with `jspm install aurelia-bootstrapper@1.0.0-beta.1.1.4`

**Comment by doktordirk** [comment]
seems to be same as https://github.com/aurelia/templating/issues/284

maybe this is the sample requested here 
https://github.com/aurelia/templating/issues/284#issuecomment-193921291

**Comment by doktordirk** [comment]
@EisenbergEffect this did cost me half a day :cry: 
- could you clarify if it is indented that doc.body is not save to access in the app.js constructor? 
- if so, is there an event raised when it is save (maybe its aurelia-composed)
- i think it's a crucial information, when it is save to access document.body and thus it should be specified in the docs when it's save and when/where on can do so

**Comment by EisenbergEffect** [comment]
It's nothing to do with body actually. It depends on what element you put the `aurelia-app` attribute. If you want to keep body's content around, simply choose another html element to place your app in. The reason body isn't safe is only because the `aurelia-app` indicates that is a location to render the app into. When it renders, it removes any content inside of that element.

**Comment by doktordirk** [comment]
i know that. but previously this was happening before the app constructor. now it's afterwards
