### ISSUE TITLE
My Aurelia RC application will not run in IE11, typescript transpiled to ES6

### ISSUE THREAD

**Issue by dkent600** [aurelia/bootstrapper#42]
My Aurelia RC application will not run in IE11, typescript transpiled to ES6.  The javascript console shows the following error

```
"(SystemJS) SyntaxError: Syntax error
Evaluating http://localhost:51323/main.js
Error loading http://localhost:51323/main.js"
```

Does not happen when transpiled for ES5.

The most relevant source code:  [Index.zip](https://github.com/aurelia/bootstrapper/files/344189/Index.zip)

**Comment by dkent600** [comment]
Here are the two main.js files, one compiled for ES5, the other for ES6:  
[main files.zip](https://github.com/aurelia/bootstrapper/files/344195/main.files.zip)

**Comment by gheoan** [comment]
IE11 does not support ES6.

**Comment by gheoan** [comment]
https://kangax.github.io/compat-table/es6/#ie11

**Comment by dkent600** [comment]
OK, I was under the impression that browsers that don't support ES6 could be made to do so with shims/polyfills (I'm using shim-es6).  Is this not, in fact, the case?

**Comment by gheoan** [comment]
Some ES6 features can be polyfilled (usually additions to the standard library such as `Array.prototype.find`) and some need a transpiler (usually syntax additions such as the `class` keyword).

**Comment by dkent600** [comment]
OK, question, if I may:  Suppose I am targeting ES6 in my `tsconfig.json`, and am including shim-es6 or core-js to polyfill the API for browsers that need it.  How does one also transpile the syntactical stuff like "class" and "=>"?  Do I need to turn on transpiling in the `config.js`?  I'm really not clear how this works....thanks for any explanations!  I believe the answer to this should be able to close this issue report.

**Comment by gheoan** [comment]
The target option in `tsconfig.json` is for what version of ES is supported by the browsers you want your application to work in. So, for example, if you want your application to work in IE11 you must change the target in `tsconfig.json` to ES5 because IE11 only supports ES5. That will translate all ES6 syntax to ES5 syntax. 

Then if you are also using features from standard library that were introduced in ES6 you need to include an polyfill. Aurelia already includes polyfills for part of ES6 standard library so you might not need `core-js` or `shim-es6`.

**Comment by dkent600** [comment]
OK, as far as I'm concerned, this issue is resolved.  Sorry for the false alarm and thank you for the explanation.
